name: butcher_core
description: core app
version: 1.0.0
author: Ahmed Masoud
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^2.3.0
  easy_localization: ^3.0.0
  edge_alerts: ^0.0.1
  equatable: ^2.0.3
 # fcm_config: ^3.0.7
  firebase_auth: ^2.0.0
 # firebase_core: ^1.3.0
 # firebase_database: ^7.1.1
 # firebase_storage: ^9.0.0
  flutter_bloc: ^7.0.1
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.0.0
  logger: ^1.0.0
  queen_validators: ^0.2.3
  textless: ^6.6.6
  url_launcher: ^6.0.9
  google_fonts: ^2.1.0
dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
